"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import { usePolling } from "@/lib/usePolling";
import { fmtNum, fmtVol, pct, cls } from "@/lib/format";

type Alert = { price?: number; volume?: number };
const alertKey = "stocks.watchlist.alerts";
const readAlerts = (): Record<string, Alert> => { try { return JSON.parse(localStorage.getItem(alertKey) || "{}"); } catch { return {}; } };

export default function WatchlistPage() {
  const [items, setItems] = useState<any[]>([]); const [loaded, setLoaded] = useState(false); const [flashes, setFlashes] = useState<Record<string, "up" | "down">>({}); const [alerts, setAlerts] = useState<Record<string, Alert>>({}); const [hits, setHits] = useState<Record<string, string[]>>({}); const [editing, setEditing] = useState(""); const [note, setNote] = useState(""); const prevPrices = useRef<Record<string, number>>({}); const dragged = useRef("");
  useEffect(() => setAlerts(readAlerts()), []);
  const load = useCallback(() => { api.watchlist().then((w) => { const nextFlashes: Record<string, "up" | "down"> = {}; const nextHits: Record<string, string[]> = {}; for (const it of w.data) { const price = it.price?.close; const previous = prevPrices.current[it.symbol]; if (price != null && previous != null && price !== previous) nextFlashes[it.symbol] = price > previous ? "up" : "down"; if (price != null) prevPrices.current[it.symbol] = price; const rule = alerts[it.symbol]; const hit = [rule?.price != null && price != null && price >= rule.price ? `Harga ≥ ${fmtNum(rule.price)}` : "", rule?.volume != null && (it.price?.volume || 0) >= rule.volume ? `Volume ≥ ${fmtVol(rule.volume)}` : ""].filter(Boolean); if (hit.length) nextHits[it.symbol] = hit; } setFlashes(nextFlashes); setHits(nextHits); setItems(w.data); setLoaded(true); }).catch(() => setLoaded(true)); }, [alerts]);
  usePolling(load, 10000);
  const saveAlert = (symbol: string, value: Alert) => { const next = { ...alerts, [symbol]: value }; if (!value.price && !value.volume) delete next[symbol]; setAlerts(next); localStorage.setItem(alertKey, JSON.stringify(next)); };
  const saveNote = async (symbol: string) => { await api.watchlistUpdate(symbol, note); setEditing(""); load(); };
  const reorder = async (target: string) => { const from = dragged.current; if (!from || from === target) return; const next = [...items]; const start = next.findIndex((item) => item.symbol === from); const end = next.findIndex((item) => item.symbol === target); next.splice(end, 0, next.splice(start, 1)[0]); setItems(next); await api.watchlistReorder(next.map((item) => item.symbol)); };
  const remove = async (symbol: string) => { await api.watchlistRemove(symbol); load(); };
  if (!loaded) return <div className="empty-state"><span className="spin" /> Memuat…</div>;
  return <div><h1 className="page-title">Watchlist</h1>{items.length === 0 ? <div className="empty-state card">Watchlist kosong. Buka halaman saham lalu klik "Add to Watchlist" untuk menambahkan.</div> : <div className="card"><div className="muted" style={{ marginBottom: 8 }}>Tarik baris untuk mengurutkan. Alert hanya aktif di browser ini saat halaman Watchlist terbuka.</div><div className="table-scroll"><table><thead><tr><th></th><th>Symbol</th><th className="num">Price</th><th className="num">Change %</th><th className="num">Volume</th><th className="num">PER</th><th>Note</th><th>Alert</th><th>Latest News</th><th></th></tr></thead><tbody>{items.map((it) => <tr key={it.symbol} draggable onDragStart={() => { dragged.current = it.symbol; }} onDragOver={(event) => event.preventDefault()} onDrop={() => reorder(it.symbol)}><td className="muted">⋮⋮</td><td><Link href={`/stock/${it.symbol}`} className="sym-badge">{it.symbol}</Link>{hits[it.symbol] && <div className="neg">{hits[it.symbol].join(" · ")}</div>}</td><td className={`num ${flashes[it.symbol] ? `flash-${flashes[it.symbol]}` : ""}`}>{it.price ? fmtNum(it.price.close) : "-"}</td><td className={`num ${cls(it.price?.change_pct)}`}>{it.price ? pct(it.price.change_pct) : "-"}</td><td className="num">{it.price ? fmtVol(it.price.volume) : "-"}</td><td className="num">{it.ratios?.per != null ? fmtNum(it.ratios.per) : "-"}</td><td>{editing === it.symbol ? <><input aria-label={`Catatan ${it.symbol}`} value={note} onChange={(event) => setNote(event.target.value)} /><button className="btn btn-sm" onClick={() => saveNote(it.symbol)}>SAVE</button></> : <button className="btn btn-sm" onClick={() => { setEditing(it.symbol); setNote(it.note || ""); }}>{it.note || "NOTE"}</button>}</td><td><input aria-label={`Alert harga ${it.symbol}`} type="number" placeholder="Harga" defaultValue={alerts[it.symbol]?.price || ""} onBlur={(event) => saveAlert(it.symbol, { ...alerts[it.symbol], price: Number(event.target.value) || undefined })} /><input aria-label={`Alert volume ${it.symbol}`} type="number" placeholder="Volume" defaultValue={alerts[it.symbol]?.volume || ""} onBlur={(event) => saveAlert(it.symbol, { ...alerts[it.symbol], volume: Number(event.target.value) || undefined })} /></td><td style={{ maxWidth: 240, overflow: "hidden", textOverflow: "ellipsis" }}>{it.latest_news ? <a href={it.latest_news.url} target="_blank" rel="noopener noreferrer">{it.latest_news.title}</a> : <span className="muted">—</span>}</td><td><button className="btn btn-sm" onClick={() => remove(it.symbol)}>✕</button></td></tr>)}</tbody></table></div></div>}</div>;
}
