"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";

export default function AIWatchlistPage() {
  const [data,setData]=useState<any>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const load=()=>api.aiWatchlistToday().then(setData).catch(e=>setError(e.message));
  useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t)},[]);
  const refresh=async()=>{setBusy(true);setError("");try{await api.aiWatchlistRefresh();await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
  const agents=(data?.data||[]).filter((x:any)=>x.method==="TRADING_AGENTS"); const paper=(data?.data||[]).filter((x:any)=>x.method==="PAPER_TRADE");
  return <div><div className="terminal-page-head"><div><span className="terminal-eyebrow">MONITOR / DAILY SETUPS</span><h1>AI WATCHLIST</h1><div className="terminal-page-meta"><span>TRADING DAY {data?.trading_date||"-"}</span><span>MARKET {data?.market?.status||"-"}</span><span>DATA AS OF {data?.generated_at?new Date(data.generated_at).toLocaleTimeString("id-ID",{hour12:false}):"-"}</span></div></div><button className="btn" onClick={refresh} disabled={busy}>{busy?"UPDATING…":"REFRESH"}</button></div>{error&&<div className="analysis-err">WATCHLIST UPDATE FAILED · {error}</div>}<div className="watchlist-overview"><Summary title="TOP AI WATCHLIST" rows={data?.data||[]}/><Summary title="METHOD OVERLAP" rows={overlap(data?.data||[])}/></div><WatchSection title="TRADINGAGENTS WATCHLIST" code="TA" rows={agents}/><WatchSection title="PAPER TRADE WATCHLIST" code="QNT" rows={paper}/></div>;
}
function overlap(rows:any[]){const map=new Map<string,any[]>();rows.forEach(r=>map.set(r.symbol,[...(map.get(r.symbol)||[]),r]));return [...map.entries()].filter(([,x])=>x.length>1).map(([symbol,x])=>({...x[0],status:"DUAL SIGNAL",score:x.map(r=>r.score).filter(Boolean).join(" / "),reasons:{positive:["TradingAgents + Paper Engine"]}}));}
function Summary({title,rows}:{title:string;rows:any[]}){return <div className="terminal-panel"><header className="terminal-panel-head"><div><span className="terminal-panel-code">AI</span><h2>{title}</h2></div></header>{rows.length?<table className="dense-table"><tbody>{rows.slice(0,6).map((r:any)=><tr key={`${r.method}-${r.symbol}`}><td><Link href={`/stock/${r.symbol}`} className="ticker-link">{r.symbol}</Link></td><td>{r.method==="TRADING_AGENTS"?"TA":"PAPER"}</td><td>{r.status}</td><td className="num">{r.score??"-"}</td></tr>)}</tbody></table>:<div className="terminal-empty">NO QUALIFIED WATCHLIST CANDIDATES</div>}</div>}
function WatchSection({title,code,rows}:{title:string;code:string;rows:any[]}){return <div className="terminal-panel watch-section"><header className="terminal-panel-head"><div><span className="terminal-panel-code">{code}</span><h2>{title}</h2></div></header>{rows.length?<div className="table-scroll"><table className="dense-table"><thead><tr><th>CODE</th><th className="num">LAST</th><th>STATUS</th><th className="num">ENTRY ZONE</th><th className="num">TP1</th><th className="num">SL</th><th className="num">R/R</th><th>WHY WATCH</th><th>DATA AS OF</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><Link href={`/stock/${r.symbol}`} className="ticker-link">{r.symbol}</Link></td><td className="num">{fmt(r.last_price)}</td><td>{r.status}</td><td className="num">{fmt(r.entry_low)}–{fmt(r.entry_high)}</td><td className="num pos">{fmt(r.tp1)}</td><td className="num neg">{fmt(r.stop_loss)}</td><td className="num">{r.risk_reward?Number(r.risk_reward).toFixed(2):"-"}</td><td>{(r.reasons?.positive||[]).join(" · ")||"Setup sedang dipantau"}</td><td className="data-time">{r.data_timestamp?new Date(r.data_timestamp).toLocaleTimeString("id-ID",{hour12:false}):"-"}</td></tr>)}</tbody></table></div>:<div className="terminal-empty">NO QUALIFIED WATCHLIST CANDIDATES</div>}</div>}
function fmt(v:any){return v==null?"-":Math.round(Number(v)).toLocaleString("id-ID")}
