"use client";

import { useEffect, useRef, useState } from "react";
import { api } from "@/lib/api";

type Item = { symbol?: string; title: string; url?: string; source?: string; published_at?: string; summary?: string; sentiment?: string };

function NewsList({ rows, aggregate = false }: { rows: Item[]; aggregate?: boolean }) {
  return rows.length ? <div className="card">{rows.map((n, i) => <div className="news-item" key={`${n.url || n.title}-${i}`}><a href={n.url} target="_blank" rel="noopener noreferrer" className="t">{aggregate && <span style={{ color: "var(--amber)" }}>[{n.symbol}] </span>}{n.title}</a><div className="m">{n.source || "Unknown"}{n.published_at ? " - " + new Date(n.published_at).toLocaleString("id-ID") : ""}{n.sentiment ? ` - ${n.sentiment.toUpperCase()}` : ""}</div>{n.summary && <div className="muted" style={{ marginTop: 3 }}>{n.summary}</div>}</div>)}</div> : <div className="empty-state card">Belum ada berita untuk filter ini.</div>;
}

export default function NewsPage() {
  const [selected, setSelected] = useState(""); const [rows, setRows] = useState<Item[]>([]); const [loaded, setLoaded] = useState(false); const [searchQuery, setSearchQuery] = useState(""); const [matches, setMatches] = useState<any[]>([]); const [showDropdown, setShowDropdown] = useState(false); const [updatedAt, setUpdatedAt] = useState<Date | null>(null); const [refreshing, setRefreshing] = useState(false); const [refreshKey, setRefreshKey] = useState(0); const [feed, setFeed] = useState<{ data: Item[]; sources: string[] }>({ data: [], sources: [] }); const [feedLoaded, setFeedLoaded] = useState(false); const [sentiment, setSentiment] = useState("all"); const [source, setSource] = useState(""); const [days, setDays] = useState("7"); const searchRef = useRef<HTMLInputElement>(null);

  useEffect(() => { let active = true; Promise.all([api.watchlist(), api.overview()]).then(([watchlist, overview]) => { const symbol = watchlist.data[0]?.symbol || overview.gainers[0]?.symbol; if (active && symbol) selectStock(symbol); }).catch(() => {}); return () => { active = false; }; }, []);
  useEffect(() => { let active = true; setFeedLoaded(false); api.newsFeed(sentiment, source || undefined, Number(days), refreshKey || undefined).then((result) => { if (active) { setFeed(result); setFeedLoaded(true); } }).catch(() => { if (active) setFeedLoaded(true); }); return () => { active = false; }; }, [sentiment, source, days, refreshKey]);
  useEffect(() => { if (!selected) return; let active = true; setRows([]); setLoaded(false); api.news(selected, refreshKey || undefined).then((r) => { if (active) { setRows(r.data); setLoaded(true); setUpdatedAt(new Date()); } }).catch(() => { if (active) setLoaded(true); }).finally(() => { if (active) setRefreshing(false); }); return () => { active = false; }; }, [selected, refreshKey]);

  const selectStock = (symbol: string) => { setSelected(symbol); setSearchQuery(symbol); setShowDropdown(false); searchRef.current?.blur(); };
  const handleSearchChange = (query: string) => { setSearchQuery(query); if (!query.trim()) { setMatches([]); setShowDropdown(false); return; } const controller = new AbortController(); window.setTimeout(() => api.stocks(query, controller.signal).then((hits) => { setMatches(hits); setShowDropdown(true); }).catch(() => { setMatches([]); setShowDropdown(false); }), 180); };
  const refresh = () => { setRefreshing(true); setRefreshKey(Date.now()); };

  return <div><div className="terminal-page-head"><div><h1 className="page-title">News</h1><span className="muted">{updatedAt ? `Diperbarui ${updatedAt.toLocaleTimeString("id-ID", { hour12: false })}` : "Memuat feed"}</span></div><button className="btn" type="button" onClick={refresh} disabled={refreshing}>{refreshing ? "MEMUAT..." : "REFRESH"}</button></div>
    <section className="terminal-panel" style={{ marginBottom: 14 }}><header className="terminal-panel-head"><div><span className="terminal-panel-code">MKT</span><h2>MARKET FEED</h2></div></header><div style={{ display: "flex", gap: 8, flexWrap: "wrap", margin: "0 0 12px" }}><select aria-label="Filter sentimen" value={sentiment} onChange={(e) => setSentiment(e.target.value)}><option value="all">SEMUA SENTIMEN</option><option value="positive">POSITIF</option><option value="negative">NEGATIF</option><option value="neutral">NETRAL</option></select><select aria-label="Filter sumber" value={source} onChange={(e) => setSource(e.target.value)}><option value="">SEMUA SUMBER</option>{feed.sources.map((item) => <option key={item} value={item}>{item}</option>)}</select><select aria-label="Filter tanggal" value={days} onChange={(e) => setDays(e.target.value)}><option value="1">24 JAM</option><option value="7">7 HARI</option><option value="30">30 HARI</option></select></div><span className="muted">Watchlist dan top gainers. URL/headline duplikat disatukan. Sentimen adalah label kata kunci, bukan analisis investasi.</span>{feedLoaded ? <NewsList rows={feed.data} aggregate /> : <div className="empty-state"><span className="spin" /> Memuat market feed...</div>}</section>
    <section className="terminal-panel"><header className="terminal-panel-head"><div><span className="terminal-panel-code">STK</span><h2>STOCK NEWS</h2></div></header><div className="search-box terminal-search"><span className="command-prefix">CMD</span><input ref={searchRef} aria-label="Cari kode atau nama saham" placeholder="TICKER / COMPANY  [ / ]" value={searchQuery} onChange={(e) => handleSearchChange(e.target.value.toUpperCase())} onFocus={() => { if (matches.length) setShowDropdown(true); }} onBlur={() => setTimeout(() => setShowDropdown(false), 150)} onKeyDown={(e) => { if (e.key === "Enter" && matches[0]) selectStock(matches[0].symbol); if (e.key === "Escape") setShowDropdown(false); }} />{showDropdown && matches.length > 0 && <div className="search-results terminal-search-results">{matches.map((s) => <button key={s.symbol} type="button" onMouseDown={() => selectStock(s.symbol)}><strong>{s.symbol}</strong> {s.company_name}</button>)}</div>}</div><span className="muted">Sumber: Google News RSS. Konten berita adalah data eksternal tidak terverifikasi.</span>{!selected ? <div className="empty-state">Menentukan saham default...</div> : !loaded ? <div className="empty-state"><span className="spin" /> Memuat...</div> : <NewsList rows={rows} />}</section>
  </div>;
}
