"use client";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
export default function PerformancePage() {
  const [strategy, setStrategy] = useState("BSJP"); const [period, setPeriod] = useState("daily"); const [method, setMethod] = useState(""); const [data, setData] = useState<any>(null);
  useEffect(() => { api.strategyPerformance(strategy, period, method || undefined).then(setData).catch(() => setData(null)); }, [strategy, period, method]);
  const rows = data?.data || []; const m = data?.combined || {};
  return <div><h1 className="page-title">STRATEGY PERFORMANCE</h1><div className="tabs">{["BSJP","BPJS"].map(x => <button className={strategy === x ? "active" : ""} onClick={() => setStrategy(x)} key={x}>{x}</button>)} </div><div className="tabs">{[["daily","DAY"],["weekly","WEEK"],["monthly","MONTH"],["yearly","YEAR"]].map(([x,label]) => <button className={period === x ? "active" : ""} onClick={() => setPeriod(x)} key={x}>{label}</button>)} </div><div className="tabs">{[["","ALL"],["TRADING_AGENTS","TRADINGAGENTS"],["PAPER_TRADE","PAPER"]].map(([x,label]) => <button className={method === x ? "active" : ""} onClick={() => setMethod(x)} key={x}>{label}</button>)}</div><p className="muted">{data ? `${data.period_start} — ${data.period_end} · calculated ${data.generated_at}` : "Loading"}</p><div className="grid grid-2"><Metric title="TRADES" value={m.trades ?? 0} /><Metric title="WIN RATE" value={m.win_rate == null ? "N/A" : `${m.win_rate}%`} /><Metric title="NET RETURN" value={`${m.net_return_pct ?? 0}%`} /><Metric title="PROFIT FACTOR" value={m.profit_factor ?? "N/A"} /></div>{rows.map((row: any) => <div className="card" key={row.method}><div className="card-title">{row.method} · {row.status}</div><p>{row.trades} trades · {row.winning_trades}W {row.losing_trades}L · Win {row.win_rate ?? "N/A"}% · Net {row.net_return_pct}% · PF {row.profit_factor ?? "N/A"}</p><p className="muted">Signals {row.signals} · Triggered {row.triggered} · Not triggered {row.not_triggered} · Open {row.open_positions}</p></div>)}</div>;
}
function Metric({ title, value }: { title: string; value: string | number }) { return <div className="card"><div className="muted">{title}</div><strong className="metric-value">{value}</strong></div>; }
