"use client";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

export default function AITradingPage() {
  const [status,setStatus]=useState<any>(null); const [history,setHistory]=useState<any[]>([]); const [jobs,setJobs]=useState<any[]>([]); const [ticker,setTicker]=useState(""); const [quick,setQuick]=useState(""); const [deep,setDeep]=useState(""); const [error,setError]=useState(""); const [matches,setMatches]=useState<any[]>([]); const [searching,setSearching]=useState(false); const [detail,setDetail]=useState<any>(null);
  const load=()=>Promise.all([api.aiTradingStatus(),api.aiTradingHistory(),api.aiTradingJobs()]).then(([s,h,j])=>{setStatus(s);setQuick(q=>q||s.quick_model);setDeep(d=>d||s.deep_model);setHistory(h);setJobs(j)}).catch(e=>setError(e.message));
  useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);
  useEffect(()=>{const query=ticker.trim();if(!query){setMatches([]);return}setSearching(true);const timer=setTimeout(()=>api.stocks(query).then(setMatches).catch(()=>setMatches([])).finally(()=>setSearching(false)),200);return()=>clearTimeout(timer)},[ticker]);
  const run=async()=>{try{await api.aiTradingAnalyze(ticker,quick,deep);load()}catch(e:any){setError(e.message)}};
  const openDetail=async(sym:string)=>{try{setDetail(await api.aiTradingAnalysis(sym))}catch(e:any){setError(e.message)}};
  return <div><div className="auto-trade-head"><div><h1 className="page-title">AI Trading</h1><p className="muted">TradingAgents research and paper-trading signals.</p></div><div className="paper-label">PAPER TRADING ONLY</div></div>{error&&<div className="analysis-err">{error}</div>}<div className="grid grid-4 auto-summary"><Stat label="Status" value={status?.enabled?"Enabled":"Disabled"}/><Stat label="9Router" value={status?.nine_router_reachable?"Connected":"Unavailable"}/><Stat label="Quick model" value={status?.quick_model||"-"}/><Stat label="Deep model" value={status?.deep_model||"-"}/></div><div className="card auto-actions"><div><strong>Manual analysis</strong><p className="muted">Runs asynchronously and does not open a trade.</p></div><div className="action-buttons"><div className="ai-ticker-picker"><input className="ai-select ai-ticker" aria-label="IDX ticker" value={ticker} onChange={e=>setTicker(e.target.value.toUpperCase())} placeholder="Search ticker or company" autoComplete="off"/>{matches.length>0&&<div className="ai-ticker-results">{matches.map((stock:any)=><button type="button" key={stock.symbol} onClick={()=>{setTicker(stock.symbol);setMatches([])}}><strong>{stock.symbol}</strong><span>{stock.company_name}</span></button>)}</div>}{searching&&<span className="ai-searching">Searching…</span>}</div><select className="ai-select" aria-label="Quick model" value={quick} onChange={e=>setQuick(e.target.value)}>{(status?.available_models||[]).filter((m:string)=>m.startsWith("cx/")||m.startsWith("gemini/")||m.startsWith("openai/")).map((m:string)=><option key={m}>{m}</option>)}</select><select className="ai-select" aria-label="Deep model" value={deep} onChange={e=>setDeep(e.target.value)}>{(status?.available_models||[]).filter((m:string)=>m.startsWith("cx/")||m.startsWith("gemini/")||m.startsWith("openai/")).map((m:string)=><option key={m}>{m}</option>)}</select><button className="btn btn-primary" disabled={!status?.enabled||!ticker.trim()} onClick={run}>Run analysis</button></div></div><div className="card"><div className="card-title">Current jobs</div><Rows rows={jobs} empty="No active jobs." onPick={openDetail}/></div><div className="card"><div className="card-title">Analysis history</div><Rows rows={history} empty="No analyses yet." onPick={openDetail}/></div>{detail&&<DetailCard d={detail} onClose={()=>setDetail(null)}/>}</div>
}
function Stat({label,value}:{label:string;value:string}){return <div className="stat"><div className="label">{label}</div><div className="value">{value}</div></div>}
function Rows({rows,empty,onPick}:{rows:any[];empty:string;onPick:(sym:string)=>void}){return rows.length===0?<p className="muted">{empty}</p>:<div className="table-scroll"><table><thead><tr><th>Ticker</th><th>Decision</th><th>Signal</th><th>Status</th><th>Runtime</th><th>Date</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="sym-badge">{r.symbol}</td><td>{r.decision||"-"}</td><td>{r.action||"-"}</td><td>{r.status}</td><td>{r.runtime_seconds?`${Number(r.runtime_seconds).toFixed(1)}s`:"-"}</td><td>{String(r.date||r.created_at||"").slice(0,10)}</td><td>{r.analysis_id?<button className="btn" onClick={()=>onPick(r.symbol)}>Detail</button>:<button className="btn" onClick={()=>onPick(r.symbol)}>Detail</button>}</td></tr>)}</tbody></table></div>}
function normalizeMarkdown(value: unknown) { return String(value || '').replace(/\r/g, '').replace(/^(?: {4}|\t)/gm, '').replace(/\n{3,}/g, '\n\n').trim(); }
function localAction(value:string){return({BUY:"BELI",SELL:"JUAL",HOLD:"TAHAN",NO_TRADE:"TIDAK TRANSAKSI"} as Record<string,string>)[value]||value} function localDecision(value:string){return({"Strong Overweight":"Sangat Overweight",Overweight:"Overweight","Market Weight":"Bobot Pasar",Underweight:"Underweight","Strong Underweight":"Sangat Underweight"} as Record<string,string>)[value]||value} function DetailCard({d,onClose}:{d:any;onClose:()=>void}){const agentOrder=["Analis Pasar / Teknikal","Analis Berita","Analis Fundamental","Manajer Riset","Rekomendasi Trader & Setup","Analisis Risiko","Keputusan Akhir Portofolio","Peneliti Bullish","Peneliti Bearish"];const ordered=(d.reasoning||[]).sort((a:any,b:any)=>{const ai=agentOrder.indexOf(a.agent);const bi=agentOrder.indexOf(b.agent);return(ai===-1?99:ai)-(bi===-1?99:bi)});
  const fmt=(v?:number|null)=>v==null?"-":v.toLocaleString("id-ID");
  const s=d.setup||{};
  return <div className="card ai-detail">
    <div className="auto-trade-head"><div><h2 className="section-title">{d.symbol} · {localAction(d.action)} <span className="muted">({localDecision(d.decision)})</span></h2><p className="muted">{String(d.date||"").slice(0,10)} · {d.runtime_seconds?`${Number(d.runtime_seconds).toFixed(0)}s`:d.status}</p></div><button className="btn" onClick={onClose}>Tutup</button></div>
    {d.action==="BUY"&&<table className="ai-setup"><thead><tr><th>Entry</th><th>Stop Loss</th><th>Take Profit</th><th>R/R</th></tr></thead><tbody><tr><td className="num">{fmt(s.entry)}</td><td className="num neg">{fmt(s.stop_loss)}</td><td className="num pos">{fmt(s.take_profit)}</td><td className="num">2.0</td></tr></tbody></table>}
    {ordered.map((r:any)=><details key={r.agent} open className="ai-reasoning"><summary>{r.agent}</summary><div className="ai-reasoning-body markdown-body"><ReactMarkdown remarkPlugins={[remarkGfm]}>{normalizeMarkdown(r.content)}</ReactMarkdown></div></details>)}
  </div>;
}
