"use client";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";

export default function AITradingPage() {
  const [status,setStatus]=useState<any>(null); const [history,setHistory]=useState<any[]>([]); const [jobs,setJobs]=useState<any[]>([]); const [ticker,setTicker]=useState("BBCA"); const [quick,setQuick]=useState(""); const [deep,setDeep]=useState(""); const [error,setError]=useState("");
  const load=()=>Promise.all([api.aiTradingStatus(),api.aiTradingHistory(),api.aiTradingJobs()]).then(([s,h,j])=>{setStatus(s);setQuick(q=>q||s.quick_model);setDeep(d=>d||s.deep_model);setHistory(h);setJobs(j)}).catch(e=>setError(e.message));
  useEffect(()=>{load();const t=setInterval(load,10000);return()=>clearInterval(t)},[]);
  const run=async()=>{try{await api.aiTradingAnalyze(ticker,quick,deep);load()}catch(e:any){setError(e.message)}};
  return <div><div className="auto-trade-head"><div><h1 className="page-title">AI Trading</h1><p className="muted">TradingAgents research and paper-trading signals.</p></div><div className="paper-label">PAPER TRADING ONLY</div></div>{error&&<div className="analysis-err">{error}</div>}<div className="grid grid-4 auto-summary"><Stat label="Status" value={status?.enabled?"Enabled":"Disabled"}/><Stat label="9Router" value={status?.nine_router_reachable?"Connected":"Unavailable"}/><Stat label="Quick model" value={status?.quick_model||"-"}/><Stat label="Deep model" value={status?.deep_model||"-"}/></div><div className="card auto-actions"><div><strong>Manual analysis</strong><p className="muted">Runs asynchronously and does not open a trade.</p></div><div className="action-buttons"><input className="ai-select ai-ticker" aria-label="IDX ticker" value={ticker} onChange={e=>setTicker(e.target.value.toUpperCase())} placeholder="BBCA" /><select className="ai-select" aria-label="Quick model" value={quick} onChange={e=>setQuick(e.target.value)}>{(status?.available_models||[]).filter((m:string)=>m.startsWith("cx/")||m.startsWith("gemini/")||m.startsWith("openai/")).map((m:string)=><option key={m}>{m}</option>)}</select><select className="ai-select" aria-label="Deep model" value={deep} onChange={e=>setDeep(e.target.value)}>{(status?.available_models||[]).filter((m:string)=>m.startsWith("cx/")||m.startsWith("gemini/")||m.startsWith("openai/")).map((m:string)=><option key={m}>{m}</option>)}</select><button className="btn btn-primary" disabled={!status?.enabled||!ticker.trim()} onClick={run}>Run analysis</button></div></div><div className="card"><div className="card-title">Current jobs</div><Rows rows={jobs} empty="No active jobs."/></div><div className="card"><div className="card-title">Analysis history</div><Rows rows={history} empty="No analyses yet."/></div></div>
}
function Stat({label,value}:{label:string;value:string}){return <div className="stat"><div className="label">{label}</div><div className="value">{value}</div></div>}
function Rows({rows,empty}:{rows:any[];empty:string}){return rows.length===0?<p className="muted">{empty}</p>:<div className="table-scroll"><table><thead><tr><th>Ticker</th><th>Decision</th><th>Signal</th><th>Status</th><th>Runtime</th><th>Date</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="sym-badge">{r.symbol}</td><td>{r.decision||"-"}</td><td>{r.action||"-"}</td><td>{r.status}</td><td>{r.runtime_seconds?`${Number(r.runtime_seconds).toFixed(1)}s`:"-"}</td><td>{String(r.date||r.created_at||"").slice(0,10)}</td></tr>)}</tbody></table></div>}
