"use client";

import { useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { fmtNum, fmtVol, pct, cls } from "@/lib/format";

interface Filters { per_max: string; pbv_max: string; roe_min: string; roa_min: string; der_max: string; revenue_growth_min: string; net_income_growth_min: string; dividend_yield_min: string; volume_min: string; price_min: string; price_max: string; rsi_min: string; rsi_max: string; above_sma200: string; }
const EMPTY: Filters = { per_max:"",pbv_max:"",roe_min:"",roa_min:"",der_max:"",revenue_growth_min:"",net_income_growth_min:"",dividend_yield_min:"",volume_min:"",price_min:"",price_max:"",rsi_min:"",rsi_max:"",above_sma200:"" };

export default function ScreenerPage() {
  const [tab,setTab]=useState<"GENERAL"|"BSJP"|"BPJS">("GENERAL"); const [method,setMethod]=useState<"PAPER_TRADE"|"TRADING_AGENTS">("PAPER_TRADE"); const [selected,setSelected]=useState<any>(null); const [filters,setFilters]=useState<Filters>(EMPTY); const [rows,setRows]=useState<any[]>([]); const [strategy,setStrategy]=useState<any>(null); const [ran,setRan]=useState(false); const [busy,setBusy]=useState(false);
  const set=(field:keyof Filters,value:string)=>setFilters(f=>({...f,[field]:value}));
  async function runGeneral(){setBusy(true);const params=new URLSearchParams();(Object.keys(filters) as (keyof Filters)[]).forEach(k=>{if(filters[k].trim())params.set(k,filters[k])});try{const r=await api.screener(params);setRows(r.data);setRan(true)}catch(e:any){alert("Screener gagal: "+e.message)}finally{setBusy(false)}}
  async function runStrategy(value:"BSJP"|"BPJS", selectedMethod = method){setBusy(true);try{setStrategy(await api.recommendationsStrategy(value,selectedMethod))}catch(e:any){setStrategy({status:"ERROR",reason:e.message})}finally{setBusy(false)}}
  const field=(label:string,key:keyof Filters,suffix="")=><div className="filter-field"><label>{label}</label><input value={filters[key]} onChange={e=>set(key,e.target.value)} placeholder={suffix}/></div>;
  return <div><div className="terminal-page-head"><div><span className="terminal-eyebrow">SCREEN / RANKING</span><h1>STOCK SCREENER</h1></div></div><div className="strategy-tabs"><button className={tab==="GENERAL"?"active":""} onClick={()=>setTab("GENERAL")}>GENERAL</button><button className={tab==="BSJP"?"active":""} onClick={()=>{setTab("BSJP");runStrategy("BSJP")}}>BSJP · BELI SORE JUAL PAGI</button><button className={tab==="BPJS"?"active":""} onClick={()=>{setTab("BPJS");runStrategy("BPJS")}}>BPJS · BELI PAGI JUAL SORE</button></div>{tab!=="GENERAL"&&<div className="method-tabs"><button className={method==="PAPER_TRADE"?"active":""} onClick={()=>{setMethod("PAPER_TRADE");runStrategy(tab,"PAPER_TRADE")}}>PAPER ENGINE</button><button className={method==="TRADING_AGENTS"?"active":""} onClick={()=>{setMethod("TRADING_AGENTS");runStrategy(tab,"TRADING_AGENTS")}}>TRADINGAGENTS</button></div>}{tab==="GENERAL"?<><div className="card" style={{marginBottom:5}}><div className="card-title">Deterministic filters · SQL / analytics</div><div className="filter-grid">{field("PER <","per_max")}{field("PBV <","pbv_max")}{field("ROE >","roe_min","%")}{field("ROA >","roa_min","%")}{field("DER <","der_max")}{field("Rev Gth >","revenue_growth_min","%")}{field("NI Gth >","net_income_growth_min","%")}{field("Div Yield >","dividend_yield_min","%")}{field("Volume >","volume_min")}{field("Price >","price_min")}{field("Price <","price_max")}{field("RSI >","rsi_min")}{field("RSI <","rsi_max")}<div className="filter-field"><label>vs SMA200</label><select value={filters.above_sma200} onChange={e=>set("above_sma200",e.target.value)}><option value="">Any</option><option value="true">Above</option><option value="false">Below</option></select></div></div><button className="btn btn-primary" onClick={runGeneral} disabled={busy}>{busy?"RUNNING…":"RUN SCREENER"}</button></div>{ran&&<GeneralResults rows={rows}/>}</>:<StrategyResults data={strategy} busy={busy} method={method} onSelect={setSelected}/>} {selected&&<ScreenerDetail row={selected} onClose={()=>setSelected(null)}/>}</div>;
}
function ScreenerDetail({row,onClose}:{row:any;onClose:()=>void}){const sections=row.reasons?.sections||[];return <div className="screener-modal-backdrop" onClick={onClose}><div className="screener-modal" onClick={e=>e.stopPropagation()}><div className="terminal-panel-head"><div><span className="terminal-panel-code">{row.method==="TRADING_AGENTS"?"TA":"QNT"}</span><h2>{row.symbol} · {row.strategy}</h2></div><button className="btn" onClick={onClose}>CLOSE</button></div><div className="screener-detail-levels"><b>ENTRY {fmtNum(row.entry_low)}–{fmtNum(row.entry_high)}</b><b className="pos">TP1 {fmtNum(row.tp1)}</b><b className="pos">TP2 {fmtNum(row.tp2)}</b><b className="neg">SL {fmtNum(row.stop_loss)}</b><b>R/R {row.risk_reward?Number(row.risk_reward).toFixed(2):"-"}</b><b>SCORE {row.score??"-"}</b></div>{sections.length?sections.map((text:string,index:number)=><section className="screener-reason" key={index}><ReactMarkdown remarkPlugins={[remarkGfm]}>{text}</ReactMarkdown></section>):<section className="screener-reason"><h3>WHY THIS PAPER SETUP</h3><div className="screener-reason-list">{(row.reasons?.positive||[]).map((text:string)=><div className="positive" key={text}>+ {text}</div>)}{(row.reasons?.negative||[]).map((text:string)=><div className="negative" key={text}>− {text}</div>)}</div><h3>CALCULATED SIGNALS</h3><div className="screener-signal-grid">{Object.entries(row.signals||{}).map(([key,value])=><div key={key}><span>{key.replaceAll("_"," ")}</span><b>{String(value)}</b></div>)}</div></section>}<div className="muted screener-detail-meta">Data: {row.data_timestamp?new Date(row.data_timestamp).toLocaleString("id-ID"):"-"} · Market: {row.market_status||"-"}</div></div></div>}
function GeneralResults({rows}:{rows:any[]}){return <div className="terminal-panel"><header className="terminal-panel-head"><div><span className="terminal-panel-code">SQL</span><h2>{rows.length} RESULTS</h2></div></header><div className="table-scroll"><table className="dense-table"><thead><tr><th>CODE</th><th className="num">PRICE</th><th className="num">CHG%</th><th className="num">VOLUME</th><th className="num">PER</th><th className="num">PBV</th><th className="num">ROE</th><th className="num">RSI</th></tr></thead><tbody>{rows.map(r=><tr key={r.symbol}><td><Link href={`/stock/${r.symbol}`} className="ticker-link">{r.symbol}</Link></td><td className="num">{fmtNum(r.price?.close)}</td><td className={`num ${cls(r.price?.change_pct)}`}>{pct(r.price?.change_pct)}</td><td className="num">{fmtVol(r.price?.volume).replace(" lembar","")}</td><td className="num">{r.ratios?.per!=null?fmtNum(r.ratios.per):"-"}</td><td className="num">{r.ratios?.pbv!=null?fmtNum(r.ratios.pbv):"-"}</td><td className="num">{r.ratios?.roe!=null?fmtNum(r.ratios.roe)+"%":"-"}</td><td className="num">{r.technicals?.rsi14!=null?fmtNum(r.technicals.rsi14):"-"}</td></tr>)}</tbody></table></div></div>}
function StrategyResults({data,busy,method,onSelect}:{data:any;busy:boolean;method:"PAPER_TRADE"|"TRADING_AGENTS";onSelect:(row:any)=>void}){if(busy)return <div className="terminal-loading">LOADING STRATEGY…</div>;if(!data||!data.data?.length)return <div className="terminal-empty">NO TRADE · NO QUALIFIED SETUP<br/><span>{data?.reason||"Belum ada hasil pada window strategy ini."}</span></div>;return <div className="terminal-panel"><header className="terminal-panel-head"><div><span className="terminal-panel-code">{data.strategy}</span><h2>{method === "TRADING_AGENTS" ? "TRADINGAGENTS PICKS" : "PAPER ENGINE PICKS"}</h2></div></header><div className="table-scroll"><table className="dense-table"><thead><tr><th>CODE</th><th className="num">ENTRY ZONE</th><th className="num">TP1</th><th className="num">TP2</th><th className="num">SL</th><th className="num">R/R</th><th className="num">SCORE</th><th>WHY</th></tr></thead><tbody>{data.data.map((r:any)=><tr key={r.id}><td><button className="ticker-link ticker-button" onClick={() => onSelect(r)}>{r.symbol}</button></td><td className="num">{fmtNum(r.entry_low)}–{fmtNum(r.entry_high)}</td><td className="num pos">{fmtNum(r.tp1)}</td><td className="num pos">{fmtNum(r.tp2)}</td><td className="num neg">{fmtNum(r.stop_loss)}</td><td className="num">{r.risk_reward?.toFixed(2)}</td><td className="num">{r.score}</td><td>{r.reasons?.positive?.join(" · ") || r.reasons?.sections?.length ? "TradingAgents analysis tersedia · klik ticker untuk detail" : "-"}</td></tr>)}</tbody></table></div></div>}
